version: "3"
services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: template
    volumes:
      - ./mongodb/init:/docker-entrypoint-initdb.d
    command: mongod --auth
  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb